### ISSUE TITLE
"submit" version does not know last page

### ISSUE THREAD

**Issue by pdebuyl** [KWARC/LaTeX-proposal#14]
How to reproduce:

    git clone https://github.com/KWARC/LaTeX-proposal
    cd LaTeX-proposal
    make

have a look at, i.e., `dfg/examples/proposal/public.pdf` and `dfg/examples/proposal/submit.pdf`. The `submit.pdf` files reports "page 1 of 0", etc. The same behavior exists in `eu/examples/fetopenstrep`.

Normally, there should be a `jobname.pdata` file in those directories but I can't find it after the build. In https://github.com/pdebuyl/FET_Proposal the file is still present after a `make -B draft` or `make -B final`. Then, `draft.pdata` has the line 

    \@pdata@def{prop}{page}{last}{17}

but `final.pdata` does not. I have no idea why despite reading carefully `proposal.sty`.

**Comment by kohlhase** [comment]
I have not been able to reproduce the behavior. When I format ```dfg/examples/proposal/submit.tex``` then I get ```page 3 of 4``` (there has been an error in ```submit.tex``` which I corrected). 

Further comments: it is not ```jobname.pdata```, but ```\jobname.pdata``` or in other words ```submit.pdata``` and that is present for me. 

Ah, I see the problem for you. You have a version of proposal.cls from Jan 14. 2015. You need to update to the repository version (or use the newly updated version from CTAN/TeXLIve). The date in ```base/proposal.cls``` should  be
```
\ProvidesClass{proposal}[2015/11/22 v1.5 Project Proposal]
```
