### ISSUE TITLE
[INFO] change how the milestones are referenced

### ISSUE THREAD

**Issue by iron76** [KWARC/LaTeX-proposal#17]
I want to change the way milestones are references. At present, the reference which I obtain by using
`\mileref{myMilestone}` is **M1**. I would like to change it to **MS1** but I can't find the line to change this reference style. Any idea?

**Comment by kohlhase** [comment]
this is already planned for, just put 
```
\makeatletter
\renewcommand\milestone@label[1]{MS{#1}}
\makeatother
```
into your preamble.

**Comment by kohlhase** [comment]
sorry for the late answer.
