### ISSUE TITLE
Error with loading both amssymb + wasysym

### ISSUE THREAD

**Issue by fmetzger** [KWARC/LaTeX-proposal#18]
Using a fully updated TeXLive 2015 (and pdflatex) the `dfgproposal.cls` throws the following error:

`/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsmath.sty:557: LaTeX Error: Command \iint already defined. [...d{\iint}{\DOTSI\protect\MultiIntegral{2}}]`
`/usr/local/texlive/2015/texmf-dist/tex/latex/amsmath/amsmath.sty:558: LaTeX Error: Command \iiint already defined. [...{\iiint}{\DOTSI\protect\MultiIntegral{3}}]`

This seems to be caused by loading both `amssymb` and `wasysym` in the `proposal.cls`, in any particular order. Only removing `wasysym` fixes it.

**Comment by kohlhase** [comment]
I am not seeing the problem, I have a fully updated TeXLive as well. worrying.

**Comment by fmetzger** [comment]
Hm, interesting, this happened to me with the `dfgproposals.cls` supplied by TeXLive and the example files from CTAN. It does not seem to occur when I directly use the dfg examples provided in this repo.

**Comment by highlando** [comment]
Same thing here.

A grep told me that `wasysym`  is loaded in the base files: `base/proposal.sty:\RequirePackage{wasysym}`

Since I don't want to touch the base files, I now use the workaround:

```
\let\iint\undefined
\let\iiint\undefined
\usepackage{amsmath,amsthm,mathrsfs,mathtools,amscd}
```

in the preamble of my `proposal.tex`.

**Comment by kohlhase** [comment]
I think that this is a good workaround for the moment.
