### ISSUE TITLE
Projekt without Acronym

### ISSUE THREAD

**Issue by spth** [KWARC/LaTeX-proposal#21]
Are projects without acronym supported?
I tried changing

```
  acronym={iPoWr},
  acrolong={\underline{I}ntelligent} {\underline{P}r\underline{o}posal} {\underline{Wr}iting},
  title=\pn: \protect\pnlong,
```

to

```
  title=test,
```

in the so called "simple" proposal DFG template. But I get:

```
! Undefined control sequence.
\prop@proposal ...RGE Acronym: {\prop@gen@acronym 
                                                  }}\\[.2cm] {\large \today ...
l.30   areas=Knowledge Management]
```

Philipp

**Comment by kohlhase** [comment]
hmmm, I never had the case. I will have a look. Thanks for the question.

**Comment by kohlhase** [comment]
Indeed, the notion of a project having an acronym is quite deeply assumed in the class. But the absence clearly should be better handled. 
So what is your intuition here? 
1. your project will never have an acronym? 
2. your project just does not have an acronym yet. 
For 1. we will have to think about what to do in the page headings, ... For 2. we just have to make better error messages/warnings, and have a default value (maybe ????). 
That would help me.

**Comment by spth** [comment]
The project will not have an acronym (like e.g. DFG SA 2908/3-1, which AFAIK was applied for using the .rtf form).

Philipp

**Comment by kohlhase** [comment]
Will you have a short name then? 
Currently, the acronym is used in the headers. What should I put there if there is no acrony? Should I leave them empty then?

**Comment by spth** [comment]
Personally, for me just leaving that space empty in the header is good enough. I guess in the long term, a short name for the headers would make sense (which maybe could default to the full name).

Philipp

**Comment by spth** [comment]
I guess a reasonable short-term fix would be to just allow an empty acronym. The only change required probably would be to omit the "Acronym:" line on the title page when the acronym is empty.

Philipp

**Comment by kohlhase** [comment]
fixed by the last commit
