### ISSUE TITLE
How to get rid of table of contents?

### ISSUE THREAD

**Issue by spth** [KWARC/LaTeX-proposal#26]
I wrote a DFG proposal using this package. But the .pdf contains a table of contents ("Inhaltsverzeichnis") on the title page. Even the examples for this class contain a table of contents.

How can I get rid of the table of contents (the DFG does not allow it)?

Philipp

**Comment by kohlhase** [comment]
sorry for the late answer, I was traveling. 
The ```submit``` option should get rid of all things the DFG does not allow.
