### ISSUE TITLE
Usage/Documentation dfgprojpapers

### ISSUE THREAD

**Issue by miili** [KWARC/LaTeX-proposal#32]
Hi there,

the syntax of `\dfgprojpapers` is not really clear to me. What does `<keys>` and `<refs>` refer to exactly?

A comma seperated list of bibtex refs does result in a single citation. Maybe a ramped up documentation with a short example would help.

thanks and best regards,

M

**Comment by kohlhase** [comment]
indeed, this was ill-documented (I had to look at the LaTeX code to remember what was going on). 
I have extended the documentation and made the sub-bibliography heading configurable. 
Thanks for raising this issue
