### ISSUE TITLE
Interaction with proposal shipped by TeXLive

### ISSUE THREAD

**Issue by hmgaudecker** [KWARC/LaTeX-proposal#40]
Thanks for a great package, it helped me on several previous applications! But I do have some trouble with current master on Ubuntu 18.04 with TeXlive 2019. 

Changing the TEXINPUTS as described in the README did not do the trick for me. The examples would still find the version shipped with TeXLive. These would fail because they use bibtex, but the Makefile always started biber. It took me a while until I realised that.

I solved this by placing LaTeX-proposal in my local texmf directory. 

Then, however, the "ed" package shipped with TeXlive is unable to handle the marginnote option, so I ended up patching that manually with what I found at https://gl.kwarc.info/kwarc/macros/tree/master/ed

It then runs through without error, but the DFG examples do not generate the title page. I will open a separate issue on that.

**Comment by kohlhase** [comment]
Sorry for the delay, busy with NFDI proposal and EU Evaluations until November 1.

**Comment by kohlhase** [comment]
I am not sure what you are asking here. The TEXINPUTS problem is a known problem for windows applications which is not specific to `*proposal.cls`. I have looked at all occurrences of bibtex in the code and it seems to be OK.

I am taking out of this that I should make a release of `ed.sty` (I was not aware that the most current version was not released).

**Comment by kohlhase** [comment]
I have externalized the remaining problem to #42

**Comment by hmgaudecker** [comment]
Thanks!

Re the first point: I am not sure about Windows and was not aware of this behaviour on Linux. In any case, the instructions here seem to stem from a time where proposal was not part of a latex-distribution; flagging possible problems due to interactions in the documentation would seem helpful to me. 

E.g., I think the problem I had with bibtex/biber is that I used the github version of the examples / makefile (called biber) but the version of proposal (shipped with texlive) that was being used expected bibtex. Took me a long time to figure it out.
