### ISSUE TITLE
No title page generated

### ISSUE THREAD

**Issue by hmgaudecker** [KWARC/LaTeX-proposal#41]
I am trying to compile the examples on master, also see #40. Ubuntu 18.04 with TeXlive 2019. 

simple-proposal/proposal.tex compiles without error, but it is missing the title page. In particular, the red disclaimer is shown, but neither 

_Neuantrag auf Sachbeihilfe
iPoWr: Intelligent Proposal Writing
Acronym: iPoWr
January 13, 2015
Michael Kohlhase
Jacobs University
Great Communicator
Power Consulting_, 

nor the table of contents.

I have read through the logfile carefully and multiple times, but I am unable to find anything that would seem related. I am stumped with regard to debugging this any further, would you have any pointers? 

I do not necessarily need the latest and greatest version, but the example also refuses to compile with proposal shipped with TeXlive. Any general pointers to get a working setup would be greatly appreciated!

**Comment by kohlhase** [comment]
Sorry for the delay, busy with NFDI proposal and EU Evaluations until November 1.

**Comment by lawa42** [comment]
Any updates on the title page issue.  I am running into the same problem and now have to use LibreOffice for writing the proposal

**Comment by kohlhase** [comment]
Sorry, will answer in the next days, have been very busy, and can now catch up.

**Comment by kohlhase** [comment]
sorry to have kept you waiting, but this is not a bug, it iis a feature (tm). 

You only get the title page, etc. iff you give the `general` option (which I had not done in `simple-proposal/proposal.tex`.
I have added that (and explained the options better in the comments). 
Merry Christmas

**Comment by hmgaudecker** [comment]
Perfect, thank you! A well-hidden feature indeed :-). Merry Christmas, too!

**Comment by lawa42** [comment]
Merry x-mas and thanks for the answer.
