### ISSUE TITLE
gitinfo2 support

### ISSUE THREAD

**Issue by JakeHertenstein** [KWARC/LaTeX-proposal#9]
How would I go about removing or disabling the native `SVN` requirement and instead use `gitinfo2`?
Currently, if I simply add `\usepackage[pcount,grumpy,mark,markifdirty]{gitinfo2}` I get a messy heading on the title page and have duplicate footers with SVN.

**Comment by highlando** [comment]
I had to source the `gitinfo2-hook.sh` first, to get the config file, namely `gitHeadInfo.gin`, in the right place:

```
cd /path/to/Latex-Proposal
source lib/gitinfo2-hook.sh
```

Maybe this info saves someone some minutes.
